image: node:10.15.3-alpine
services:
  - docker:dind

stages:
  - build
  - test
  - package
  
before_script:
    - apk update && apk add ffmpeg imagemagick && rm -rf /var/cache/apk/*
    - npm install --silent --progress=false

cache:
  paths:
   - node_modules/
   
variables: 
    CONTAINER_IMAGE: registry.gitlab.com/$CI_PROJECT_PATH
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    NODE_ENV: 'test'
    REGION: 'us-east-1'
    BUCKET: 'blue-stream-test'
    S3_IS_PATH_STYLE: '1'
    ACCESS_KEY_ID: 'minio'
    SECRET_ACCESS_KEY: 'minio123'
    S3_ENDPOINT: 'http://minio:9000'


lint:
  stage: build
  script:
    npm run tslint

test:
  stage: test
  services:
  - minio:latest
  script:
  - npm test

review:
  stage: package
  image: docker:latest
  cache: {}
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:current .
    - docker push $CONTAINER_IMAGE:current
  only:
   - master

release:
  stage: package
  image: docker:latest
  cache: {}
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull $CONTAINER_IMAGE:latest || true
    - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_TAG --tag $CONTAINER_IMAGE:latest .
    - docker push $CONTAINER_IMAGE:$CI_COMMIT_TAG
    - docker push $CONTAINER_IMAGE:latest
  only:
   - tags
  except:
   - branches
